# Referenced from https://gitlab.com/forrestab/dotnet-gitlab-ci/blob/master/.gitlab-ci.yml
image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build

before_script:
  - "dotnet restore"

build:
  stage: build
  script:
    - "dotnet build"
    - "dotnet build -c Release"
