jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
    - os: windows

language: csharp
mono: none
dotnet: 3.1.302
git:
  submodules: true
install:
  - dotnet restore
script:
  - dotnet build